### ISSUE TITLE
Where can I change the appearance location?

### ISSUE THREAD

**Issue by Bxnnet** [php-flasher/php-flasher#88]
Hey I just started using Flasher in an Symfony project but I cant find an option to change the notification locations. Currently it appears at the right side on the top but I would like it to be on the right bottom location.
Is that possible?

Thanks in advance!

**Comment by yoeunes** [comment]
Hello @Bxnnet, I'm sorry for the late response.
You can do it for all your notification at once in the config file 

```yaml
# config/packages/flasher.yaml
flasher:
    default: flasher
    themes:
        flasher:
            options:
                position: bottom-right
```

or for individual notification:
```php
public function action(FlasherInterface $flasher): Response
{
    $flasher
        ->option('position', 'bottom-right')
        ->addSuccess('Data has been saved successfully!');

```
